# Generated by Django 4.1 on 2022-10-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8, unique=True)),
                ('brand', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
